<a href="https://colab.research.google.com/github/Shahzadtextilian/AI-Model-Training/blob/master/MultiVarianceLinear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/AI/Student_Performance.csv")
df.rename(columns={'Extracurricular Activities':'Extracurricular_Activities','Hours Studied':'Hours_Studied','Previous Scores':'Previous_Scores', 'Sleep Hours':'Sleep_Hours','Sample Question Papers Practiced':'Papers_Practiced','Performance Index':'Performance_Index'},inplace=True)
df.head(10)

,Hours_Studied,Previous_Scores,Extracurricular_Activities,Sleep_Hours,Papers_Practiced,Performance_Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
5,3,78,No,9,6,61.0
6,7,73,Yes,5,6,63.0
7,8,45,Yes,4,6,42.0
8,5,77,No,8,2,61.0
9,4,89,No,4,0,69.0

In [ ]:
#df = df.drop(columns=['Extracurricular Activities'])
df.drop(columns=['Extracurricular_Activities'], inplace=True)
df

,Hours_Studied,Previous_Scores,Sleep_Hours,Papers_Practiced,Performance_Index
0,7,99,9,1,91.0
1,4,82,4,2,65.0
2,8,51,7,2,45.0
3,5,52,5,2,36.0
4,7,75,8,5,66.0
...,...,...,...,...,...
9995,1,49,4,2,23.0
9996,7,64,8,5,58.0
9997,6,83,8,5,74.0
9998,9,97,7,0,95.0
9999,7,74,8,1,64.0

In [ ]:
lr=linear_model.LinearRegression()
lr.fit(df[['Hours_Studied','Previous_Scores','Sleep_Hours','Papers_Practiced']],df.Performance_Index)

LinearRegression()

In [ ]:
#test the model
lr.predict([[2,40,6,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([15.54447177])

In [ ]:
lr.score(df[['Hours_Studied','Previous_Scores','Sleep_Hours','Papers_Practiced']],df.Performance_Index)
lr.coef_

array([2.85342921, 1.01858354, 0.47633298, 0.1951983 ])

In [ ]:
lr.intercept_

np.float64(-33.76372609079468)

In [ ]:
#y=wx+b
Predicted =2.85342921*2+ 1.01858354*40+ 0.47633298*6+ 0.1951983*0-33.76372609079468
print(Predicted)

15.54447180920532